language: node_js
node_js:
  - "8.8"
install:
  - npm install
jobs:
  include:
    - stage: test
      script: ./test
    - # stage name not required, will continue to use `test`
      script: ./minify
